// The source scene contains inherited Japanese labels. All lettering painted on
// world textures passes through this copy layer so the Jaipur scene uses only
// English and Hindi, including small props and generated atlas details.
const foreignScript = /[\u3005\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af\uff66-\uff9d]/u;
const foreignRuns = /[\u3005\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af\uff66-\uff9d]+/gu;

const copy = {
  '桜ヶ丘': 'Gulabi Nagar', 'さくらがわ': 'Gulabi River', '桜川': 'Gulabi River', '桜 川': 'GULABI RIVER',
  '山桜': 'Sanganer', '春日野': 'Sanganer', '花見台': 'Chandpole', 'さくら坂': 'Pink City Lane',
  'さくら': 'Gulabi', '桜': 'Gulabi', 'はるかぜ': 'Gulabi', 'みどり': 'Hariyali', 'あおぞら': 'Neela Aasmaan',
  'गुलाबी नगर駅': 'गुलाबी नगर स्टेशन', 'गुलाबी नगर स्टेशन前': 'गुलाबी नगर स्टेशन चौक',
  'गुलाबी नगर警察署': 'गुलाबी नगर पुलिस', 'गुलाबी नगर産 コシヒカリ': 'गुलाबी नगर चावल',
  '駅周辺案内図': 'STATION AREA MAP', '駅前': 'STATION CHOWK', '駅': 'STATION', '改札口': 'TICKET GATE',
  '乗車位置': 'BOARD HERE', '番線': 'PLATFORM', '時刻表': 'TIMETABLE', '路線図': 'ROUTE MAP',
  '発車': 'DEPARTURE', '到着': 'ARRIVAL', '普通': 'LOCAL', '各駅停車': 'LOCAL', '快速': 'EXPRESS',
  '出口': 'EXIT', '入口': 'ENTRY', '北口': 'NORTH EXIT', '南口': 'SOUTH EXIT', '東口': 'EAST EXIT',
  '西口': 'WEST EXIT', '切符': 'TICKET', 'きっぷ': 'TICKET', '乗車券': 'TICKET', '券売機': 'TICKET MACHINE',
  '乗り場': 'BOARDING', 'バス停': 'BUS STOP', 'バス': 'BUS', 'タクシー': 'TAXI', '自転車': 'CYCLE',
  '駐輪場': 'CYCLE PARKING', '駐車場': 'PARKING', '公衆電話': 'PUBLIC PHONE', 'トイレ': 'TOILET',
  'お手洗い': 'TOILET', '窓口': 'COUNTER', '案内': 'INFORMATION', '現在地': 'YOU ARE HERE',
  'ご案内': 'INFORMATION', 'ご利用ありがとうございます': 'THANK YOU FOR TRAVELLING',
  '危 険': 'DANGER', '危険': 'DANGER', '注意': 'CAUTION', '高電圧注意': 'HIGH VOLTAGE',
  '線路内': 'ON TRACKS ', '立入禁止': 'NO ENTRY', '進入禁止': 'NO ENTRY', '関係者以外': 'STAFF ONLY',
  '緊急連絡先': 'EMERGENCY CONTACT', '非常': 'EMERGENCY', '消火器': 'FIRE EXTINGUISHER',
  '消火栓': 'FIRE HYDRANT', '火気厳禁': 'NO OPEN FLAMES', '禁止': 'PROHIBITED', '止まれ': 'STOP',
  '一時停止': 'STOP', '徐行': 'SLOW', '通学路': 'SCHOOL ZONE', '歩行者優先': 'PEDESTRIANS FIRST',
  '歩TO者優先': 'PEDESTRIANS FIRST', '左側通行': 'KEEP LEFT', '右岸': 'RIGHT BANK',
  'この先': 'AHEAD', '道路': 'ROAD', '川': 'RIVER', '橋': 'BRIDGE', '堤': 'RIVER WALK',
  '観光協会': 'TOURISM OFFICE', '商店会': 'MARKET ASSOCIATION', '町内会': 'NEIGHBOURHOOD GROUP',
  '内会': 'NEIGHBOURHOOD GROUP', '警察署': 'POLICE', '交番': 'POLICE POST', '小学校': 'SCHOOL',
  '郵便局': 'POST OFFICE', '郵便': 'POST', '電力': 'ELECTRIC', '不動産': 'PROPERTY',
  '月極PARKING': 'MONTHLY PARKING', '月極': 'MONTHLY', '空きあり': 'SPACE AVAILABLE',
  '売地': 'LAND FOR SALE', '約': 'ABOUT', '全長': 'LENGTH', '右': 'RIGHT', '左': 'LEFT',
  '本': 'BOOKS', '書店': 'BOOKSHOP', '雑誌': 'MAGAZINES', '週刊': 'WEEKLY', '月刊': 'MONTHLY',
  '新聞': 'NEWSPAPER', '漫画': 'COMICS', 'コミック': 'COMICS', '新刊': 'NEW ARRIVALS',
  '花屋': 'FLOWERS', '花': 'FLOWERS', 'バラ': 'ROSES', 'チューリップ': 'TULIPS',
  'ラナンキュラス': 'RANUNCULUS', 'スイートピー': 'SWEET PEAS', 'かすみ草': 'BABY’S BREATH',
  'マーガレット': 'DAISIES', 'アジサイ': 'HYDRANGEAS', '春のBOUQUETS': 'SPRING BOUQUETS',
  '春限定': 'SPRING SPECIAL', '春': 'SPRING', '夏': 'SUMMER', '秋': 'AUTUMN', '冬': 'WINTER',
  '夏まつり': 'SUMMER FESTIVAL', '春まつり': 'SPRING FESTIVAL', '祭り': 'FESTIVAL',
  '主催': 'HOSTED BY', '会場': 'VENUE', '集合': 'MEET HERE',
  '商売繁盛': 'MAY BUSINESS FLOURISH', '家内安全': 'FAMILY WELLBEING',
  '交通安全': 'ROAD SAFETY', '春の交通安全運動': 'SPRING ROAD SAFETY',
  '無病息災': 'GOOD HEALTH', '合格祈願': 'BEST OF LUCK', '必勝祈願': 'GOOD LUCK',
  '学業成就': 'SUCCESS IN STUDIES', '心願成就': 'MAY YOUR WISH COME TRUE',
  '奉　納': 'OFFERING', '奉納': 'OFFERING', 'おみくじ': 'FORTUNE', 'お守り': 'BLESSINGS',
  '神社': 'MANDIR', '神': 'SHRI', '社': 'MANDIR',
  'おいしい': 'DELICIOUS', 'ようこそ': 'WELCOME', 'いらっしゃいませ': 'WELCOME',
  'ありがとうございます': 'THANK YOU', 'ご来店': 'VISITING', 'おすすめ': 'RECOMMENDED',
  '本日の': 'TODAY’S', '今日': 'TODAY', '新発売': 'NEW', '特売中': 'SPECIAL OFFER',
  '特売': 'SPECIAL', '新入荷': 'JUST ARRIVED', '年中無休': 'OPEN DAILY', '営業中': 'OPEN',
  '定休日': 'CLOSED', '営業時間': 'OPENING HOURS', '水曜日': 'WEDNESDAY',
  '月曜日': 'MONDAY', '火曜日': 'TUESDAY', '木曜日': 'THURSDAY', '金曜日': 'FRIDAY',
  '土曜日': 'SATURDAY', '日曜日': 'SUNDAY', '日月火水木金土': 'SMTWTFS',
  '卯月': 'APRIL', '4月': 'APRIL', '月号': 'ISSUE', '午前': 'AM', '午後': 'PM',
  'ご自由にお使いください': 'PLEASE USE FREELY', 'お気軽にどうぞ': 'PLEASE COME IN',
  'ごみ': 'WASTE', 'ゴミ': 'WASTE', 'もえるごみ': 'GENERAL WASTE', 'もやすごみ': 'GENERAL WASTE',
  'ペットボトル': 'PLASTIC BOTTLES', 'プラスチック': 'PLASTIC', 'かん・びん': 'CANS & GLASS',
  '古紙・布': 'PAPER & CLOTH', '紙パック': 'CARTONS', '分別': 'SORT WASTE',
  'ゴミの投げ捨て': 'NO LITTERING', 'やめましょう': 'PLEASE KEEP CLEAN',
  'ペットのフンは持ち帰りましょう': 'CLEAN UP AFTER PETS', '河川愛護会': 'RIVER CARE GROUP',
  'ふれあい緑地': 'COMMUNITY GARDEN', '市民農園': 'COMMUNITY GARDEN',
  '花壇にはいらないでね': 'PLEASE KEEP OFF FLOWER BEDS', '区画利用者以外の立ち入りはご遠慮ください': 'GARDEN MEMBERS ONLY',
  'バケツ': 'BUCKET', 'ほうき': 'BROOM', 'はたき': 'DUSTER', 'ちりとり': 'DUSTPAN',
  '日用品': 'DAILY ESSENTIALS', '調味料': 'SPICES', '缶詰': 'CANNED GOODS',
  'インスタント': 'INSTANT FOOD', 'お米': 'RICE', '新米': 'FRESH RICE', '精米': 'MILL RICE',
  'コシヒカリ': 'LOCAL RICE', '産': 'LOCAL', '冷たいお飲み物': 'COLD DRINKS',
  '冷凍食品': 'FROZEN FOOD', 'アイスクリーム': 'ICE CREAM', 'アイス': 'ICE CREAM',
  'おやつ': 'SNACKS', '駄菓子': 'SWEETS', 'だがし': 'SWEETS', 'かご': 'BASKET',
  'カレー': 'CURRY', 'せんべい': 'NAMKEEN', '洗剤': 'DETERGENT', 'のり': 'SEAWEED',
  'ティッシュ': 'TISSUES', 'うどん': 'NOODLES', 'マッチ': 'MATCHES', 'キャラメル': 'CARAMEL',
  'サイダー': 'SODA', 'クッキー': 'BISCUITS', 'ビスケット': 'BISCUITS',
  'ほうじ茶': 'ROASTED TEA', '玄米茶': 'RICE TEA', '煎茶': 'GREEN TEA', '抹茶': 'MATCHA',
  'お茶': 'CHAI', '茶': 'CHAI', 'ラテ': 'LATTE', 'カフェラテ': 'CAFE LATTE',
  '微糖': 'LIGHTLY SWEET', '無糖': 'UNSWEETENED', '水・炭酸': 'WATER & SODA',
  '炭酸水': 'SODA WATER', 'ジュース': 'JUICE', 'レモン': 'LEMON', 'オレンジ': 'ORANGE',
  'いちご': 'STRAWBERRY', 'ぶどう': 'GRAPE', 'トマト': 'TOMATO', 'のむヨーグルト': 'DRINKING CURD',
  'つめた〜い': 'CHILLED', 'あったか': 'HOT', '乳飲料': 'MILK DRINK',
  '醤油ढाबा': 'मसाला ढाबा', '塩ढाबा': 'पनीर ढाबा', 'DALढाबा': 'दाल ढाबा',
  'PANEERメン': 'PANEER NOODLES', 'つけ麺': 'MASALA NOODLES', '半チャーハン': 'VEG FRIED RICE',
  '冷やし中華': 'COLD NOODLES', 'ライス': 'RICE', '大盛り': 'LARGE', '味玉': 'EXTRA EGG',
  '替え玉': 'EXTRA PORTION', '生ビール': 'FRESH LASSI', 'ビール': 'LASSI',
  '食券をお買い求めください': 'ORDER AT THE COUNTER', '食券': 'ORDER HERE',
  '千 Rs札': '1000 Rs NOTE', '硬貨': 'COINS', 'おつり': 'CHANGE',
  '水はセルフサービスです': 'SELF SERVICE WATER', 'ご来店THANK YOU': 'THANK YOU FOR VISITING',
  '厨房': 'KITCHEN', '厨': 'KIT', '房': 'CHEN', 'こしょう': 'PEPPER', '酢': 'VINEGAR',
  '醤油': 'SAUCE', 'ラー油': 'CHILLI OIL', '塩': 'SALT',
  'みたらし': 'GHEWAR', '練り切り': 'PEDA', 'もなか': 'BARFI', 'さくらもち': 'GULAB JAMUN',
  '急須': 'TEAPOT', '器': 'CROCKERY', '包装承ります': 'GIFT WRAPPING', 'ご贈答に': 'FOR GIFTING',
  'ベル': 'BELL', 'ライト': 'LIGHT', 'カギ': 'LOCK', '部品': 'PARTS', 'チューブ': 'TUBE',
  'タイヤ各種': 'CYCLE TYRES', 'タイヤ交換': 'TYRE CHANGE', 'ブレーキ調整': 'BRAKE SERVICE',
  '新車': 'NEW CYCLE', '中古車': 'USED CYCLE', '修理受付': 'REPAIRS',
  '整備済み': 'SERVICED', '整備済': 'SERVICED', '防犯登録': 'REGISTRATION',
  'インチ': 'INCH', '即日': 'SAME DAY', '自動ドア': 'AUTOMATIC DOOR',
  '空車': 'AVAILABLE', '車': 'CAR', '車道': 'ROAD', '有限会社': 'SERVICES',
  '水道工事・給湯器・リフォーム': 'PLUMBING & REPAIRS',
  '一丁目': 'WARD 1', '二丁目': 'WARD 2', '三丁目': 'WARD 3', '四丁目': 'WARD 4',
  '丁目': 'WARD', '第': 'NO. ', '一番': 'NO. 1', '一個': 'ONE', '三個入': 'PACK OF 3',
  '一八〇': '180', '一六〇': '160', '一五〇': '150', '一三〇': '130', '二〇〇': '200',
  '二六〇': '260', '二五〇': '250', '八〇〇': '800', '三二〇〇': '3200',
  '二八〇〇': '2800', '二五〇〇': '2500', '四五〇〇': '4500',
  '〇': '0', '一': '1', '二': '2', '三': '3', '四': '4', '五': '5',
  '六': '6', '七': '7', '八': '8', '九': '9', '十': '10', '百': '100', '千': '1000',
  '・': ' · ', '〜': '–', 'ー': '–', '（': '(', '）': ')', '、': ', ', '。': '. ',
};

Object.assign(copy, {
  'ガス': 'GAS', '宅配ボックス': 'PARCEL BOX', '出してください': 'PLEASE PUT OUT',
  '押し売りお断り': 'NO SOLICITING', '風': 'BREEZE', '順番にお並びください': 'PLEASE QUEUE HERE',
  '凡 例': 'KEY', '押して歩きましょう': 'PLEASE WALK YOUR CYCLE',
  '大切にしましょう': 'PLEASE TAKE CARE', '迷い猫を': 'MISSING CAT',
  '探しています': 'PLEASE HELP FIND', 'さがしています': 'PLEASE HELP FIND',
  '赤い首輪に鈴をつけています': 'RED COLLAR WITH A BELL',
  '赤い首輪をしています': 'WEARING A RED COLLAR', 'お心当たりの方は': 'IF YOU HAVE SEEN HER',
  '書道教室': 'CALLIGRAPHY CLASS', '書': 'WRITE', '習': 'LEARN',
  '生徒募集中': 'NEW STUDENTS WELCOME', '収集はありません': 'NO COLLECTION',
  '盆踊り大会': 'COMMUNITY DANCE FESTIVAL', 'गुलाबी नगर公園': 'गुलाबी नगर पार्क',
  '防災訓練': 'SAFETY DRILL', 'ご家族でご参加ください': 'FAMILIES WELCOME',
  'गुलाबी नगरえきまえ': 'गुलाबी नगर स्टेशन चौक', '平 日': 'WEEKDAYS',
  '市民病院前': 'CITY HOSPITAL', '運動公園': 'SPORTS PARK',
  '放置しないでください': 'PLEASE DO NOT LEAVE HERE', '取集時刻': 'COLLECTION TIMES',
  '電話帳': 'PHONE DIRECTORY', 'गुलाबी नगर地区': 'गुलाबी नगर क्षेत्र', '緊急通報': 'EMERGENCY CALL',
  '水道修理': 'PLUMBING REPAIRS', '山吹歯科医院': 'JAIPUR DENTAL CLINIC',
  '各種保険取扱': 'INSURANCE SERVICES', '御食事処はな': 'HANA EATERY',
  'はなまる薬局': 'HARIYALI PHARMACY', '処方せん受付': 'PRESCRIPTIONS HERE',
  '美容室ひだまり': 'PINK CITY SALON', 'ことり保育園': 'LITTLE BIRDS NURSERY',
  '園児募集中': 'ENROLMENT OPEN', '見学随時': 'VISIT ANYTIME',
  'ピアノ教室': 'MUSIC LESSONS', 'ドルチェ音楽院': 'DOLCE MUSIC SCHOOL',
  '体験レッスン': 'TRIAL LESSONS', '高圧': 'HIGH VOLTAGE',
  '持ちかえろ': 'TAKE IT HOME', '防犯カメラ': 'SECURITY CAMERA',
  '作動中': 'IN USE', '水のトラブル': 'WATER REPAIRS', 'ポイ捨て': 'NO LITTERING',
  'ひったくり': 'BEWARE OF THEFT', 'ネットをかけよう': 'COVER WITH A NET',
  'गुलाबी नगर防犯協会': 'GULABI NAGAR COMMUNITY WATCH',
  'でんせんの': 'OVERHEAD WIRES', 'ちかくで': 'KEEP CLEAR',
  'フンは': 'PET WASTE', '持ち帰ろう': 'TAKE IT HOME',
  'さわるな': 'DO NOT TOUCH', 'のぼるな': 'DO NOT CLIMB',
  'みまもり': 'COMMUNITY WATCH', '隊': 'TEAM',
  '子どもたちを': 'OUR CHILDREN', 'みんなで': 'TOGETHER',
  'みまもろう': 'KEEP SAFE', '防犯灯': 'SAFETY LIGHT',
  'गुलाबी नगर幹': 'GULABI NAGAR MAIN', '東町支': 'EAST WARD',
  '線路北': 'NORTH OF TRACKS', '北町支': 'NORTH WARD',
  '北町': 'NORTH WARD', '東町': 'EAST WARD',
  'ねこのおひるね': 'CAT NAPPING', '防 災 倉 庫': 'EMERGENCY STORE',
  '保管品': 'SUPPLIES', '工事中': 'WORK IN PROGRESS',
  'ご迷惑をおかけします': 'SORRY FOR THE INCONVENIENCE',
  '下水道管の点検をしています': 'DRAINAGE PIPE INSPECTION', '下 水': 'DRAIN',
  '中村家': 'SHARMA FAMILY', '鈴木工務店': 'KUMAR BUILDERS',
  '地蔵尊': 'श्री गणेश', '絵馬掛所': 'WISHES', '隊員募集中': 'VOLUNTEERS WELCOME',
  '夕方の見守りに': 'EVENING COMMUNITY WATCH', 'ご協力ください': 'PLEASE HELP',
  '合格できますように': 'MAY I PASS MY EXAMS', 'ゆうと': 'AARAV',
  '家族みんなが': 'MAY OUR FAMILY', '元気で過ごせますように': 'STAY HEALTHY',
  '中村': 'SHARMA', '恋愛成就': 'LOVE & JOY', '先輩と': 'WITH MY FRIEND',
  'もっと話せますように': 'MAY WE TALK MORE', 'お店が': 'MAY THE SHOP',
  '長く続きますように': 'THRIVE FOR YEARS', 'おばあちゃんが': 'MAY GRANDMOTHER',
  'ずっと元気でいますように': 'STAY WELL', 'गुलाबी नगर中 野球部': 'GULABI NAGAR CRICKET CLUB',
  '毎日の通学が': 'MAY THE DAILY SCHOOL JOURNEY',
  '安全でありますように': 'BE SAFE', 'はると': 'AARAV',
  '元気な赤ちゃんが': 'MAY A HEALTHY BABY', '生まれますように': 'BE BORN',
  '佐藤': 'MEHTA', '数学のテストで': 'IN THE MATHS TEST', 'りこ': 'RIYA',
  '絵がもっと': 'MAY MY DRAWINGS', '上手になりますように': 'GET BETTER',
  'あおい': 'ANAYA', 'ことしこそ': 'THIS YEAR', 'パパ': 'PAPA',
  '良縁祈願': 'GOOD FORTUNE', 'すてきな人と': 'MAY I MEET',
  '出会えますように': 'SOMEONE KIND', '看護学校に': 'NURSING SCHOOL',
  '受かりますように': 'MAY I BE ADMITTED', 'まい': 'MAYA',
  'ポチが': 'MOTI', '長生きしますように': 'MAY HE LIVE LONG',
  'けんた': 'KUNAL', '諸願成就': 'WISHES GRANTED',
  '友だちと': 'WITH MY FRIENDS', 'また同じクラスに': 'IN THE SAME CLASS AGAIN',
  'ひな': 'HINA', '開運招福': 'GOOD FORTUNE', 'なりますように': 'MAY IT HAPPEN',
  '鈴木': 'KUMAR', 'ピアノの発表会': 'MUSIC RECITAL',
  'うまくいきますように': 'MAY IT GO WELL', 'ゆい': 'TARA',
  'みんな': 'EVERYONE', '笑顔でいられますように': 'MAY WE KEEP SMILING',
  '田中家': 'SINGH FAMILY', 'そうた': 'DEV', '東京の大学で': 'AT JAIPUR UNIVERSITY',
  'がんばれますように': 'MAY I DO MY BEST', 'れん': 'VEER',
  '縁結び': 'KIND CONNECTIONS', '大好きな人と': 'WITH SOMEONE I LOVE',
  'गुलाबी नगर高校': 'GULABI NAGAR SCHOOL', '新しい家で': 'IN OUR NEW HOME',
  '仲よく暮らせますように': 'MAY WE LIVE HAPPILY', '小林': 'JAIN',
  '稲荷': 'GANESH',
  'みるく': 'MILK', 'おしるこ': 'SWEET MILK', 'つぶたっぷり': 'RICH & CREAMY',
  '売切': 'SOLD OUT', 'やさしい甘さ': 'GENTLY SWEET',
  '管理番号': 'MACHINE NO.', '故障の際はご連絡ください': 'CALL FOR SERVICE',
  'タッチ': 'TOUCH', '販売中': 'AVAILABLE', 'リサイクルにご協力ください': 'PLEASE RECYCLE',
  '異常を見つけたときは': 'IF YOU NOTICE A PROBLEM',
  'すぐにご連絡ください': 'PLEASE CALL IMMEDIATELY',
  '危　険': 'DANGER', '上り出発': 'UP DEPARTURE', '下り出発': 'DOWN DEPARTURE',
  '上り場内': 'UP APPROACH', '下り場内': 'DOWN APPROACH',
  '少年ソラ': 'YOUNG SKY', 'ねこびより': 'CAT DAYS', 'まちかど': 'STREET CORNER',
  '鉄道のたび': 'RAIL JOURNEYS', 'おうちごはん': 'HOME COOKING',
  'カメラ散歩': 'PHOTO WALKS', 'ねこ': 'CAT', '夕焼け': 'SUNSET',
  '発売': 'ON SALE', 'ナポリタン': 'MASALA PASTA', 'ブレンド': 'HOUSE BLEND',
  '自家製プリン': 'HOMEMADE CUSTARD', '勝手口': 'STAFF DOOR',
  'アレンジ': 'ARRANGEMENTS', '入荷しました': 'FRESH ARRIVALS', '母の日': 'MOTHER’S DAY',
  'じゃがスティック': 'POTATO STICKS', 'ふわマスク': 'SOFT MASK',
  'ハミガキ': 'TOOTHPASTE', 'ポテトチップス': 'POTATO CHIPS',
  'うすしお': 'LIGHT SALT', 'えびせん': 'MASALA CRISPS', 'しお味': 'SALTED',
  'わさびチップ': 'SPICY CHIPS', '辛口': 'SPICY', 'ラムネグミ': 'FRUIT GUMMIES',
  'ふわふわ': 'SOFT', 'チョコクランチ': 'CHOCOLATE CRUNCH',
  'ホット': 'HOT', 'ミックスナッツ': 'MIXED NUTS', '素焼き': 'ROASTED',
  'ふんわり': 'FLUFFY', 'あんぱん': 'SWEET BUN', 'こしあん': 'SWEET FILLING',
  'ジャスミン': 'JASMINE', 'ミネラル': 'MINERAL', 'ブラック': 'BLACK',
  'カフェオレ': 'MILK COFFEE', 'メロン': 'MELON', 'みかん': 'ORANGE',
  'きつね': 'SPICED', 'たぬき': 'CRISPY', 'やきそば': 'FRIED NOODLES',
  'バナナ': 'BANANA', '幕の内弁当': 'VEG THALI', '唐揚げ弁当': 'CHICKEN THALI',
  '焼鮭弁当': 'FISH THALI', '親子丼': 'RICE BOWL', '梅': 'PICKLE',
  '鮭': 'FISH', 'ツナマヨ': 'MAYO', '高菜': 'GREENS', 'おかか': 'SPICED',
  '明太子': 'CHILLI', '昆布': 'SEAWEED', 'まちあるき': 'CITY WALKS',
  '釣りの友': 'FISHING', '旅と温泉': 'TRAVEL & WELLNESS',
  '将棋世界風': 'GAMES', '手芸と暮らし': 'CRAFT & LIVING',
  '星空ガイド': 'NIGHT SKY', 'パズル王': 'PUZZLES',
  'ねこ日和': 'CAT DAYS', '放課後通信': 'AFTER SCHOOL',
  '家電ナビ': 'HOME TECH', '最新': 'LATEST', '号': 'ISSUE',
  '風の手紙': 'LETTERS ON THE WIND', '猫と暮らす': 'LIVING WITH CATS',
  '星を数えて': 'COUNTING STARS', '海辺の町': 'A TOWN BY THE SEA',
  '青い傘': 'THE BLUE UMBRELLA', 'ひだまり日記': 'AFTERNOON DIARY',
  '雨上がり': 'AFTER THE RAIN', '遠い灯': 'DISTANT LIGHT',
  '鉄道の歴史': 'HISTORY OF RAIL', 'ソラの冒険': 'SKY ADVENTURES',
  '魔法学園': 'THE MAGIC SCHOOL', '探偵ミナト': 'DETECTIVE MINA',
  '宇宙の果て': 'EDGE OF SPACE', 'ねこ侍': 'THE BRAVE CAT',
  '料理の達人': 'THE MASTER COOK', '竜の騎士': 'THE DRAGON KNIGHT',
  'ひみつ基地': 'SECRET BASE', '異世界食堂': 'THE OTHER CAFE',
  'ロボ研': 'ROBOT LAB', '山の家': 'THE HILL HOUSE',
  '新書': 'NEW BOOKS', '選書': 'SELECTED BOOKS',
  'ばんそうこう': 'BANDAGES', 'ヘアゴム': 'HAIR TIES',
  'イヤホン': 'EARPHONES', '歯ブラシ': 'TOOTHBRUSH',
  '店長': 'MANAGER', 'しおり ご自由に': 'FREE BOOKMARKS',
  'モンブラン': 'CHESTNUT CAKE', 'プリン': 'CUSTARD', 'ラッピング': 'GIFT WRAP',
  '期間限定': 'LIMITED TIME', 'ドリンク': 'DRINKS', '合計': 'TOTAL',
  'ホットスナック': 'HOT SNACKS', '中華まん': 'STEAMED BUNS',
  'レジ': 'BILLING', 'マルチ端末': 'SERVICE KIOSK',
  'お取引を': 'PLEASE SELECT', 'お選びください': 'A SERVICE',
  'できたて': 'FRESHLY MADE', 'からあげ': 'CRISPY BITES',
  'ご利用いただけます': 'ACCEPTED HERE', '時間営業': 'HOURS OPEN',
  'あります': 'AVAILABLE', '開催中': 'ON NOW',
  '枠内にお願いします': 'PLEASE KEEP WITHIN MARKINGS',
  '点検': 'INSPECTION', 'ヘルメットをかぶろう': 'WEAR A HELMET',
  '修理中': 'UNDER REPAIR', '事務所': 'OFFICE',
  '各種': 'ALL KINDS', 'サイズ': 'SIZES', '承ります': 'WELCOME',
  '各種キャッシュレス決済 ご利用いただけます': 'DIGITAL PAYMENTS ACCEPTED',
  'クレジット': 'CARD', '食料品': 'GROCERIES', '日用雑貨': 'DAILY GOODS',
  '米穀': 'RICE & GRAINS', 'たばこ': 'TOBACCO',
  'ヒバリ印': 'GULABI BRAND', '蚊とり線香': 'MOSQUITO COILS',
  'コトリ石鹸': 'SOFT SOAP', 'お肌すべすべ': 'SOFT ON SKIN',
  'つめたい': 'COLD', 'ハナビ': 'SPARK', 'ひだまり': 'SUNSHINE',
  '少年': 'YOUNG', 'ソラマメ': 'GREEN PEAS', 'まんが': 'COMICS',
  '盆踊り': 'COMMUNITY DANCE', 'たまご': 'EGGS', 'キャベツ': 'CABBAGE',
  'さくまる': 'GULABI', 'マスコット': 'MASCOT',
  'ご自由にお取りください': 'PLEASE TAKE ONE', '山': 'HILL',
  'どれでも': 'ANY', 'きなこ棒': 'SWEET STICKS', 'ラムネ': 'SODA',
  'ガム': 'GUM', 'あめ': 'SWEETS', 'くじ': 'LUCKY DRAW',
  '特製': 'HOUSE SPECIAL', 'はじめました': 'NOW SERVING', 'サイン': 'SIGNATURE',
  'おうげつどう': 'GULABI MITHAI', 'あつあつ': 'FRESH & HOT',
  'つぶあん': 'SWEET FILLING', '贈答用': 'FOR GIFTING',
  '詰め合わせ': 'ASSORTED BOX', '御進物': 'GIFT BOX', '湯呑': 'TEA CUP',
  '有人改札': 'STAFFED GATE', '両 停止位置': 'TRAIN STOP POSITION',
  '緑化委員会のみなさん': 'COMMUNITY GARDENERS', 'おねがい': 'PLEASE',
  'とめないでください': 'DO NOT PARK HERE', '動輪の記念碑': 'RAILWAY MEMORIAL',
  '節水にご協力を': 'PLEASE SAVE WATER', '黄色い線の内側で': 'BEHIND THE YELLOW LINE',
  'お待ちください': 'PLEASE WAIT', 'おやめください': 'PLEASE AVOID',
  'ドアにはさまれると': 'KEEP CLEAR OF DOORS',
  'お忘れ物に': 'CHECK YOUR BELONGINGS',
  'お忘れ物のお問い合わせは': 'FOR LOST PROPERTY',
  'わたしのすきな गुलाबी नगर': 'MY GULABI NAGAR',
  'みお': 'MIRA', 'ひなの': 'HINA', '掲 示 板': 'NOTICE BOARD',
  '変わります': 'HAS CHANGED', '迷い猫': 'MISSING CAT',
  '見かけた方は': 'IF YOU HAVE SEEN HER',
  '清掃ボランティア': 'CLEANUP VOLUNTEERS', '落とし物': 'LOST PROPERTY',
  '水色の水筒': 'BLUE WATER BOTTLE', 'गुलाबी नगर図書館': 'GULABI NAGAR LIBRARY',
  '記念スタンプ': 'SOUVENIR STAMP',
  '押したあとはフタをしめてね': 'PLEASE CLOSE AFTER STAMPING',
  '来訪記念': 'VISIT SOUVENIR', '置き傘': 'SHARED UMBRELLAS',
  '使ったらお返しください': 'PLEASE RETURN AFTER USE',
  '沿線おでかけ情報': 'PLACES ALONG THE LINE', '運賃表': 'FARE CHART',
  '線路北の道': 'NORTH TRACK ROAD', '紙幣': 'NOTES',
  '呼出': 'CALL', '係員呼出': 'CALL STAFF',
  'ご希望のボタンを押してください': 'SELECT YOUR TICKET', '取消': 'CANCEL',
  'ダイヤ改正': 'REVISED TIMETABLE', '清掃': 'CLEANUP',
  'ボランティア': 'VOLUNTEERS', '落とし物の': 'LOST PROPERTY',
  'ご協力をお願いします': 'PLEASE HELP US', '発売中': 'ON SALE',
  '火災報知機': 'FIRE ALARM', '強く押す': 'PRESS FIRMLY',
  'ボタン': 'BUTTON', '緊急時に押してください': 'PRESS IN EMERGENCY',
  '助役': 'STATION SUPERVISOR', '合図用具': 'SIGNAL EQUIPMENT',
  '定期券': 'SEASON TICKET', '遺失物': 'LOST PROPERTY',
  '点検記録': 'INSPECTION LOG', '安全通達': 'SAFETY NOTICE',
  '設備台帳': 'EQUIPMENT REGISTER', '精算記録': 'ACCOUNTS LOG',
  '払戻し': 'REFUND', '精算': 'FARE ADJUSTMENT', '領収書': 'RECEIPT',
  '回数券': 'MULTI-RIDE PASS', '始業点検表': 'OPENING CHECKLIST',
  '忘れ物 受付簿': 'LOST PROPERTY LOG', '沿線': 'ALONG THE LINE',
  'ハイキング': 'WALKING', 'マップ': 'MAP', '伝 言 板': 'MESSAGE BOARD',
  'おかあさんへ　塾のあと帰ります': 'MUM, I WILL BE HOME AFTER CLASS',
  'おこさまの手を': 'HOLD CHILDREN’S HANDS',
  'गुलाबी नगर工場': 'GULABI NAGAR DEPOT',
  '日帰り入浴プラン 好評': 'DAY TRIPS ALONG THE LINE',
  '通話はご遠慮ください': 'PLEASE KEEP CALLS QUIET',
  'みやこ シティサイクル': 'JAIPUR CITY CYCLE',
  '4月6日〜15日': '6–15 APRIL',
  '桜ソーダ': 'GULABI SODA', 'さくらソーダ': 'GULABI SODA',
  'さくらドリンクス': 'GULABI DRINKS', 'さくらラテ': 'GULABI LATTE',
  'गुलाबी नगर市民農園': 'गुलाबी नगर सामुदायिक बाग',
  'गुलाबी नगरふれあい緑地': 'गुलाबी नगर सामुदायिक बाग',
  'गुलाबी नगर ふれあいりょくち': 'GULABI NAGAR COMMUNITY GARDEN',
  'ソーダ': 'SODA', 'コーヒー': 'COFFEE', 'スープ': 'SOUP',
  'チャージ': 'TOP UP', 'スポーツ': 'SPORTS', 'エナジー': 'ENERGY',
  'ベーカリー': 'BAKERY', 'クリームソーダ': 'CREAM SODA',
  'なった時などに押してください': 'PRESS IF A VEHICLE IS STUCK',
  'ふれあいりょくち': 'COMMUNITY GARDEN',
  '月': 'MONTH', '火': 'FIRE', '水': 'WATER', '木': 'WOOD', '金': 'METAL',
  '時': 'HR', 'み': 'MI', '願': 'WISH', 'もえる': 'GENERAL WASTE',
  '時間': 'HOURS', '田': 'श', '味': 'FLAVOUR',
  'おすい': 'SEWER', '汚水': 'SEWER', '雨水': 'RAINWATER',
  '仕切弁': 'WATER VALVE', '制水弁': 'WATER VALVE',
  'ガ': 'GAS', '下': 'BELOW', '工': 'WORK',
});

Object.assign(copy, {
  'Gulabi橋': 'GULABI BRIDGE', 'コーポगुलाबी नगर': 'GULABI NAGAR RESIDENCES',
  '駅前Gulabi Bazaar (main street)': 'Gulabi Bazaar (main street)',
  '駅前Gulabi Bazaar': 'GULABI BAZAAR', 'Gulabi堤': 'GULABI RIVER WALK',
  'Gulabi堤 桜並木': 'GULABI RIVER PROMENADE',
  'Gulabi堤の桜並木': 'FLOWERING RIVER WALK',
  'Gulabi堤の桜が': 'FLOWERS BY THE RIVER',
  'Gulabi堤のごみ拾い': 'RIVER WALK CLEANUP',
  'Gulabi堤 桜並木 約1.2km': 'GULABI RIVER WALK · 1.2 KM',
  '花壇の花や桜の木を': 'THE FLOWERS AND TREES',
  '駅前の大桜': 'THE STATION SQUARE TREE',
  'Neighbourhood Mandirのしだれ桜': 'THE MANDIR GARDEN TREE',
  '夕方は灯籠に灯りがともります。': 'THE LAMPS GLOW IN THE EVENING.',
  '電車と桜をいっしょに撮れる': 'FRAME THE TRAIN WITH THE FLOWERS',
  '人気の撮影スポットです。': 'A FAVOURITE PHOTO SPOT.',
  '会場  Station Chowk・Gulabi堤': 'VENUE · STATION CHOWK & RIVER WALK',
  '模擬店・和太鼓・野点・スタンプラリー': 'FOOD STALLS · MUSIC · CHAI · STAMP TRAIL',
  'Gulabiバス': 'GULABI BUS', '土・休日': 'WEEKENDS',
  'Gulabiバス株式会社  営業所 गुलाबी नगर': 'GULABI BUS DEPOT · गुलाबी नगर',
  'Gulabiバス  路線図': 'GULABI BUS ROUTE MAP',
  '紙くず・その他': 'PAPER & OTHER WASTE',
  'गुलाबी नगर水道サービス': 'गुलाबी नगर जल सेवा',
  'はるかぜ不動産': 'PINK CITY PROPERTY',
  '学習塾さくらゼミ': 'GULABI STUDY CENTRE',
  '白鳥クリーニング': 'PINK CITY LAUNDRY',
  'ワイシャツ一枚から': 'ONE SHIRT OR MANY',
  '内科・小児科': 'GENERAL & CHILD HEALTH',
  '定食・丼もの': 'MEALS & RICE BOWLS',
  'カット・カラー': 'CUT & COLOUR', 'Gulabi電力': 'GULABI ELECTRIC',
  'たこあげ・つり': 'KITES & FISHING LINES',
  'しないでね Gulabi電力': 'KEEP CLEAR · GULABI ELECTRIC',
  'コレクション 全6種': 'SIX TO COLLECT',
  '救急セット・担架': 'FIRST AID & STRETCHER',
  'ヘルメット・かけや': 'HELMETS & TOOLS',
  '有志一同': 'COMMUNITY VOLUNTEERS',
  'Station Chowk・Gulabi堤': 'STATION CHOWK · GULABI RIVER WALK',
  '防犯パトロール': 'COMMUNITY PATROL',
  'いい一年に': 'A GOOD YEAR AHEAD', 'ずっと一緒に': 'ALWAYS TOGETHER',
  '吹奏楽コンクール': 'SCHOOL MUSIC FESTIVAL',
  'はるかぜCHAI': 'GULABI CHAI', 'コーン': 'CORN',
  'ポタージュ': 'SOUP', 'ティー': 'TEA',
  'あったか〜い': 'WARM', 'あったか〜いも あります': 'WARM DRINKS AVAILABLE',
  '交通系IC・電子マネー': 'CARD & DIGITAL PAYMENTS',
  'Gulabi Nagar 公式キャラクター': 'GULABI NAGAR MASCOT',
  'さくらドリンク': 'GULABI DRINK',
  'コミックさくら': 'GULABI COMICS', 'ゲーム通信': 'GAMES TODAY',
  'ガーデン': 'GARDEN', 'ショートケーキ': 'STRAWBERRY CAKE',
  '小倉トースト': 'SWEET TOAST',
  'いちごのショートケーキ': 'STRAWBERRY CAKE',
  'ミニブーケ': 'MINI BOUQUET', 'BREADジー': 'DAISIES',
  'カーネーション': 'CARNATIONS',
  'さくらクッキー': 'GULABI BISCUITS',
  'コーンスナック': 'CORN SNACKS', 'チーズ': 'CHEESE',
  'ポップコーン': 'POPCORN', 'バター醤油': 'BUTTER MASALA',
  'カラムーチョ風': 'SPICY CRISPS', '6枚切': 'SIX SLICES',
  'MILKティー': 'MILK TEA', 'ピーチ': 'PEACH',
  'グレープ': 'GRAPE', 'シーフード': 'SEAFOOD',
  'ハンバーグ弁当': 'VEG CUTLET THALI',
  '週刊はるかぜ': 'GULABI WEEKLY',
  '週刊ベースボール': 'CRICKET WEEKLY',
  '空色ノート': 'SKY BLUE NOTEBOOK',
  '青春ブルー': 'BLUE DAYS', '本屋大賞ノミネート': 'AWARD NOMINEE',
  '重版出来!': 'BACK IN PRINT!',
  '単3電池': 'AA BATTERIES', '単4電池': 'AAA BATTERIES',
  'ボールペン': 'BALLPOINT PEN', 'USBケーブル': 'USB CABLE',
  '文芸 · エッセイ': 'FICTION · ESSAYS',
  'NEW BOOKSコーナー': 'NEW BOOKS CORNER',
  '図書カード使えます': 'BOOK VOUCHERS ACCEPTED',
  'ショート': 'SHORT CAKE', 'ガトーショコラ': 'CHOCOLATE CAKE',
  'チーズケーキ': 'CHEESECAKE', 'ロール': 'SWISS ROLL',
  'フルーツタルト': 'FRUIT TART', '本日のケーキ': 'TODAY’S CAKE',
  'ケーキセット': 'CAKE & CHAI',
  'ユーカリ': 'EUCALYPTUS',
  'フラワーキーパー  鮮度保持中': 'FRESH FLOWERS',
  'フラワーレッスン': 'FLORAL WORKSHOP',
  '春のさくらフェア': 'GULABI SPRING FAIR',
  'イートインスペース': 'SEATING AREA',
  'びん・かん': 'BOTTLES & CANS',
  'コンサート': 'CONCERT TICKETS',
  'マルチコピー': 'PRINT & COPY', 'コピー': 'COPY',
  '対象商品でポイント2倍': 'DOUBLE POINTS ON SELECT ITEMS',
  '増量中!': 'EXTRA INSIDE!',
  '各種電子マネー · クレジットカード': 'CARDS & DIGITAL PAYMENTS',
  'ソフトクリーム': 'SOFT SERVE', '電子マネー': 'DIGITAL PAYMENTS',
  'Gulabi醤油': 'GULABI MASALA', '1パック': '1 PACK',
  '1玉': '1 PIECE', 'Gulabiビール': 'GULABI LASSI',
  '6個': '6 PIECES',
  '4月4日(土)・5日(日)  会場：Gulabi堤': '4–5 APRIL · GULABI RIVER WALK',
  '夜桜ライトアップ 18:00〜21:00 / गुलाबी रेल': 'EVENING LIGHTS 18:00–21:00 · गुलाबी रेल',
  'ホームでの': 'ON THE PLATFORM',
  '春のスタンプラリー': 'SPRING STAMP TRAIL',
  'あつめて記念品をもらおう！': 'COLLECT STAMPS FOR A GIFT!',
  'さくら散歩マップ': 'GULABI WALKING MAP',
  '傘・スマートフォン・定期券など': 'UMBRELLAS · PHONES · PASSES',
  'गुलाबी रेल お客さまセンター': 'गुलाबी रेल सहायता केंद्र',
  '駅構内・ホームは全面NO SMOKING': 'NO SMOKING IN THE STATION',
  '電車': 'TRAIN', '桜並木': 'FLOWERING AVENUE',
  'いこう。': 'LET’S GO.', '見ごろです！': 'IN BLOOM!',
  'ノート': 'NOTEBOOK', 'カン・ビン': 'CANS & BOTTLES',
  '2両': '2 CARS', '軍手・袋を配ります': 'GLOVES & BAGS PROVIDED',
  'キーボックス': 'KEY BOX', '車いす用スロープ': 'WHEELCHAIR RAMP',
  '3時半　桜の木の下で待ってる': 'MEET BY THE TREE AT 3:30',
  'スクールゾーン': 'SCHOOL ZONE',
  'Gulabi車輌 2019': 'GULABI RAIL · 2019',
  '新学期生 募集中！': 'ENROLMENT OPEN!',
  '桜あんぱん': 'GULABI SWEET BUN',
  '車内マナー': 'ONBOARD COURTESY',
  '季刊 さくらBOOKS': 'GULABI BOOKS QUARTERLY',
  'レッサーBREADダの赤ちゃん誕生': 'RED PANDA CUB BORN',
  'ICカードでスムーズにご乗車': 'TAP YOUR CARD TO BOARD',
  'オートライト INC. TAX': 'AUTO LIGHT · INC. TAX',
  'Gulabiの水': 'GULABI WATER', 'GulabiのWATER': 'GULABI WATER',
  '樹齢およそ八十年のソメイヨシノ。': 'THIS OLD TREE HAS SHADED THE CHOWK FOR DECADES.',
  '三毛猫（メス）': 'TRICOLOUR FEMALE CAT',
  '名前：こはる  3さい': 'NAME: GUDIYA · AGE 3',
  '平日  10:30  15:00': 'WEEKDAYS · 10:30 · 15:00',
  '土休日  11:00': 'WEEKENDS · 11:00',
  '110  警察': '100 · POLICE', '119  消防・救急': '112 · EMERGENCY',
  '寄贈  平成三年度 卒業生一同': 'GIFTED BY THE SCHOOL COMMUNITY',
  '賃貸・売買・管理': 'RENT · BUY · MANAGE',
  '小・中・高 個別指導': 'TUTORING FOR ALL GRADES',
  'チャーム 全8種': 'EIGHT CHARMS TO COLLECT',
  'ぼんぼり点灯 18:00〜21:00': 'EVENING LIGHTS · 18:00–21:00',
  '80点とれますように': 'MAY I SCORE 80 MARKS',
  '一発合格！': 'MAY I PASS FIRST TIME!',
  '朝の一杯に。': 'A FRESH START TO THE DAY.',
  '3ポット ₹500': '3 POTS · ₹500', '鉢 ₹2,800': 'PLANTER · ₹2,800',
  'レシピ100': '100 RECIPES', '続々入荷!': 'MORE ARRIVING!',
  '5個入り ₹238': 'PACK OF 5 · ₹238',
  '16日': '16TH', '15日': '15TH',
  '昭和三十二年～平成八年': '1957–1996',
  '徒歩12分': '12 MIN WALK', '4/2 ホームにて': '4/2 · ON THE PLATFORM',
  '毎週土曜 14:00〜': 'SATURDAYS · FROM 14:00',
  '対象：3さい〜': 'AGES 3+', '定期 2026': 'PASS · 2026',
});

const orderedCopy = Object.entries(copy).sort((a, b) => b[0].length - a[0].length);
const fallback = 'गुलाबी नगर';

export function localizeSceneText(value) {
  const original = String(value);
  if (!foreignScript.test(original)) return original;
  let result = original;
  for (const [source, translation] of orderedCopy) {
    if (result.includes(source)) result = result.replaceAll(source, translation);
  }
  // A few tiny inherited prop captions have no useful translation. Never paint
  // their glyphs; retain any English/Hindi around them or use the place name.
  result = result.replace(foreignRuns, '')
    .replaceAll('　', ' ').replaceAll('！', '!').replaceAll('：', ':')
    .replaceAll('～', '–').replaceAll('。', '.').replaceAll('、', ', ')
    .replace(/([\p{Script=Devanagari}])([A-Za-z])/gu, '$1 $2')
    .replace(/([A-Za-z])([\p{Script=Devanagari}])/gu, '$1 $2')
    .replace(/\s{2,}/g, ' ').trim();
  return result || fallback;
}

export function hasForeignScript(value) { return foreignScript.test(String(value)); }
